[package]
name = "caiven-studio"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "caiven-studio"
path = "src/main.rs"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
caiven-core = { workspace = true }
caiven-cart = { workspace = true }
caiven-vm = { workspace = true }
image = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
tauri-runtime = { workspace = true }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"

[target.'cfg(debug_assertions)'.dependencies]
tauri-plugin-webdriver-automation = "0.1"
toml = { workspace = true }
ureq = { workspace = true }
wry = { workspace = true }
